version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-sistema-moedas
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend-network

  webapi:
    build: .
    container_name: backend_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MeuBancoDocker;User Id=SA;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    networks:
      - backend-network

volumes:
  sql_data:

networks:
  backend-network:
